### ISSUE TITLE
Error when api use "application/json"

### ISSUE THREAD

**Issue by cavoixanha** [Fyb3roptik/swaggomnia#5] opened 2019-07-02 03:24 UTC
### Expected behavior
should add parameters correctly
### Current behavior
```
  :/api/trash:
    post:
      tags:
      - "Create"
      summary: "FLOL New"
      consumes:
        - "application/json"
      parameters:
      - name: "Accept"
        in: "header"
        type: "string"
        description: ""
        required: true
      - name: "Referer"
        in: "header"
        type: "string"
        description: ""
        required: true
      - name: "Origin"
        in: "header"
        type: "string"
        description: ""
        required: true
      - name: "keyapi"
        in: "header"
        type: "string"
        description: ""
        required: true
      - name: "User-Agent"
        in: "header"
        type: "string"
        description: ""
        required: true
      - name: "Content-Type"
        in: "header"
        type: "string"
        description: ""
        required: true
      responses:
        200:
          description: "successful operation"
```
### Steps to reproduce the behavior
```
{
            "_id": "req_da6b437b035543d78816c68d0ac9a359",
            "authentication": {},
            "body": {
                "mimeType": "application/json",
                "text": "{\"trashs\":[{\"obj_type\":\"VTODO\",\"obj_id\":\"e36eedfd-ebce-484c-ab51-b34c521e8e94\"}]}"
            },
            "created": 1560918399752,
            "description": "",
            "headers": [
                {
                    "id": "pair_9ef12f649a7c46ed82d34f7285fa24ef",
                    "name": "Accept",
                    "value": "application/json, text/plain, */*"
                },
                {
                    "id": "pair_8606f209d0fd40eab95808087cdcb17e",
                    "name": "Referer",
                    "value": "http://localhost:3003/"
                },
                {
                    "id": "pair_16984c2649d54acb9e1584d7f8f212de",
                    "name": "Origin",
                    "value": "http://localhost:3003"
                },
                {
                    "id": "pair_7a17f9c6ea284f6abcb8acec986ebc66",
                    "name": "keyapi",
                    "value": "d496129aa0e2270fea037284f3601cf8"
                },
                {
                    "id": "pair_2452da517b604e83b50abd063c1062eb",
                    "name": "User-Agent",
                    "value": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.90 Safari/537.36"
                },
                {
                    "id": "pair_7c52c30428504544a2a73836baf42b3a",
                    "name": "Content-Type",
                    "value": "application/json"
                }
            ],
            "isPrivate": false,
            "metaSortKey": -1560918399752,
            "method": "POST",
            "modified": 1560918478646,
            "name": "Old",
            "parameters": [],
            "parentId": "fld_b3e04dff86f84c179e5f7d5b4f28bd49",
            "settingDisableRenderRequestBody": false,
            "settingEncodeUrl": true,
            "settingRebuildPath": true,
            "settingSendCookies": true,
            "settingStoreCookies": true,
            "url": "http://localhost:8057/api/v1/trash",
            "_type": "request"
        }
```

**Comment by Fyb3roptik** [comment] 2019-07-03 00:17
I am not understanding your issue here. It looks as if the header params are adding correctly

**Comment by cavoixanha** [comment] 2019-07-03 18:06
Param should is body json
`{"trashs":[{"obj_type":"VTODO","obj_id":"e36eedfd-ebce-484c-ab51-b34c521e8e94"}]}"`

**Comment by Fyb3roptik** [comment] 2019-07-03 20:09
I am still unclear about the issue here. I see the header params came through just fine. Am I missing something?

**Comment by cavoixanha** [comment] 2019-07-04 06:11
I think should parse to properties of requestBody is correctly
```
post:
  tags:
    - Trash
  summary: Create Trashed
  security:
    - ApiKeyAuth: []
  operationId: createTrashed
  description: Create Trashed
  requestBody:
    content:
      application/json:
        schema:
          type: object
          required:
            - trashs
          properties:
            trashs:
              type: array
              items:
                required:
                  - obj_id
                  - obj_type
                properties:
                  obj_id:
                    $ref: './parameters/post.yaml#/obj_id'
                  obj_type:
                    $ref: './parameters/post.yaml#/obj_type'
                  sync_token:
                    $ref: './parameters/post.yaml#/sync_token'
                  status:
                    $ref: './parameters/post.yaml#/status_trash'
                  trash_time:
                    $ref: './parameters/post.yaml#/trash_time'
                  ref:
                    $ref: './parameters/post.yaml#/ref
```

**Comment by Fyb3roptik** [comment] 2019-07-08 15:34
Again, no idea what the issue is here. Closing because I cannot reproduce anything on this

**Closed by Fyb3roptik** 2019-07-08 15:34 UTC
